name: Keep Render App Awake

on:
  schedule:
    - cron: "*/14 * * * *" # runs every 14 minutes
  workflow_dispatch: # allows manual run

jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - name: Ping Render App
        run: |
          echo "Pinging Render app..."
          curl -s -o /dev/null -w "%{http_code}" https://password-vault-k9uv.onrender.com
