name: Keep Render App Awake
on:
  schedule:
    - cron: "*/13 * * * *"  # runs every 13 minutes (fixed!)
  workflow_dispatch: # allows manual run

jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - name: Ping Render App
        run: |
          echo "Pinging Render app..."
          RESPONSE=$(curl -s -o /dev/null -w "%{http_code}" https://password-vault-k9uv.onrender.com)
          echo "Response code: $RESPONSE"
          if [ "$RESPONSE" -eq 200 ] || [ "$RESPONSE" -eq 301 ] || [ "$RESPONSE" -eq 302 ]; then
            echo "✅ App is awake!"
          else
            echo "⚠️ Unexpected response: $RESPONSE"
          fi
